apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    # Since testing in minikube it does not support ReadWriteMany and ReadOnlyMany because of host path
    # minikube supports single node cluster
    - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  hostPath:
    path: /data
    type: DirectoryOrCreate
